### ISSUE TITLE
SysCallError 104

### ISSUE THREAD

**Issue by ilinuxadmin** [Backblaze/B2_Command_Line_Tool#262]
Today I have received an error while I was trying to sync my backup directory.
I have upgraded b2 command line from 6.6 to 6.9 but the issue still exist.
My OS: Debian 8 x64

My command: `b2 sync /home/FTP/Backup/Mail b2://MyBucketName`
error log:

```
ERROR:b2.b2http:_translate_errors has intercepted an unexpected exception
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 46, in _translate_errors
    response = fcn()
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 173, in do_post
    return self.session.post(url, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 883, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 852, in send
    self.sock.sendall(datablock)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 253, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 242, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1182, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')
ERROR:b2.b2http:_translate_errors has intercepted an unexpected exception
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 46, in _translate_errors
    response = fcn()
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 173, in do_post
    return self.session.post(url, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 883, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 852, in send
    self.sock.sendall(datablock)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 253, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 242, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1182, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')
ERROR:b2.b2http:_translate_errors has intercepted an unexpected exception
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 46, in _translate_errors
    response = fcn()
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 173, in do_post
    return self.session.post(url, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 883, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 852, in send
    self.sock.sendall(datablock)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 253, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 242, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1182, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')
ERROR:b2.sync.action:an exception occurred in a sync action   2.54 MB/s
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/b2/sync/action.py", line 40, in run
    self.do_action(bucket, reporter)
  File "build/bdist.linux-x86_64/egg/b2/sync/action.py", line 75, in do_action
    progress_listener=SyncFileReporter(reporter)
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 343, in upload
    upload_source, file_name, content_type, file_info, progress_listener
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 419, in _upload_large_file
    part_sha1_array = [interruptible_get_result(f)['contentSha1'] for f in part_futures]
  File "build/bdist.linux-x86_64/egg/b2/utils.py", line 60, in interruptible_get_result
    return future.result(timeout=1.0)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 507, in _upload_part
    input_stream
  File "build/bdist.linux-x86_64/egg/b2/raw_api.py", line 389, in upload_part
    return self.b2_http.post_content_return_json(upload_url, headers, data_stream)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 175, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 102, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 82, in _translate_errors
    raise UnknownError(repr(e))
UnknownError: Unknown error: SysCallError(104, 'ECONNRESET')

```

**Comment by ppolewicz** [comment]
This is a part of #224

**Comment by ilinuxadmin** [comment]
I have upgraded b2 command line in my other server and I have the same issue.
# b2 version
b2 command line tool, version 0.6.9

I dont think this is relevant to the issue #224 
Any suggestion how to fix it?

**Comment by ilinuxadmin** [comment]
Unfortunately I cannot even upload a single file anymore!!!
$ b2 upload_file --threads 30 MyBucket Backup01.tar.gz  Backup01.tar.gz 
error : 
`ERROR: Unknown error: SysCallError(104, 'ECONNRESET')`

**Comment by svonohr** [comment]
Is this a new issue that occurred after upgrading from a previous version? The ECONNRESET error usually means that there is something wrong with your connection to the B2 servers. Because of issue #224 these errors currently don't result in a retry, but they shouldn't happen often anyway. Maybe you can try uploading with fewer threads?

**Comment by bwbeach** [comment]
We had some trouble on the servers this morning.  That could be the cause.

**Comment by ilinuxadmin** [comment]
I have just tried it with two different servers from two different regions but the result is the same!
It stops after uploading 800 something MB.

$b2 upload_file EmailBackupVault Mail_10232016.tar.gz.gpg_bfb5740772510a9442346abb45941c7a ```
Mail_10232016.tar.gz.gpg_bfb5740772510a9442346abb45941c7a
Mail_10232016.tar.gz.gpg_bfb5740772510a9442346abb45941c7a:  62%|███████████████████████████████████▏                     | 855M/1.38G [00:47<00:29, 18.0MB/s]
ERROR: Unknown error: SysCallError(104, 'ECONNRESET')
```
Do you still have issues at your end?

**Comment by ilinuxadmin** [comment]
After all this was a systematic issue from BackBlaze according to their reply to my ticket:
---
Hello,

Thank you for letting us know. Our team has found an issue that is currently impacting some users' B2 usage. This is a high priority issue and we are currently working as quickly as possible to resolve this. We apologize for this inconvenience. 

I don't have an exact ETA on the fix, but again, we are aware and working on the problem and will resume normal service as soon as we can.
---

And after 3 days I received another reply:
---
We have addressed this problem and believe you shouldn't see as many upload failures anymore. Receiving upload failures is normal, but we don't expect more than 1-2% of uploads to experience a failure. Please let us know if this problem has been resolved for you.
---

But unfortunately the issue is not solved completely and I can only upload a single file, if I use sync option it would fail with "ECONNRESET" error.
I hope this would be fixed too...

**Comment by ppolewicz** [comment]
Since the situation has changed, could you please provide new logs?

**Comment by ilinuxadmin** [comment]
I just checked the sync option again and it worked , of course I received a few warnings and a few files were skipped from upload (about 10%) which were uploaded with re-run the sync command.
It seems like the issue is resolved.
I will test it on other servers and let you know the result.

**Comment by RealityFork** [comment]
I am still getting the same error, b2 0.6.8


`ERROR:b2.b2http:_translate_errors has intercepted an unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 46, in _translate_errors
    response = fcn()
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 173, in do_post
    return self.session.post(url, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 883, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 852, in send
    self.sock.sendall(datablock)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 253, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 242, in _send_until_done                        [70/103]
    return self.connection.send(data)
SysCallError: (104, 'Connection reset by peer')
ERROR:b2.sync.action:an exception occurred in a sync action
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/action.py", line 40, in run
    self.do_action(bucket, reporter)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/action.py", line 75, in do_action
    progress_listener=SyncFileReporter(reporter)
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 339, in upload
    return f.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 361, in _upload_small_file
    sha1_sum, file_info, input_stream
  File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 362, in upload_file
    return self.b2_http.post_content_return_json(upload_url, headers, data_stream)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 175, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 102, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 82, in _translate_errors
    raise UnknownError(repr(e))
UnknownError: Unknown error: SysCallError(104, 'Connection reset by peer')
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 887, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 691, in run
    max_workers=max_workers
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 221, in sync_folders
    raise CommandError('sync is incomplete')
CommandError: sync is incomplete
ERROR: sync is incomplete`

**Comment by MrLizard** [comment]
I have been receiving this error with some of our automated backup scripts. I've been wondering why they haven't been working the past few weeks.

`Backup_2016-12-19.tar.gz:  22%| | 8.80G/40.0G [04:50<17:09, 30.3MB/s]
ERROR: Unknown error: SysCallError(104, 'ECONNRESET')`

Our scripts like to get to around 20-30% then they get the ECONNRESET error. Although it only seems to be happening with the larger files. Small files under 1g seem to be unaffected, and files over 25g seem to be a big issue.

**Comment by ppolewicz** [comment]
syscallerror were python2-specific and there was no cure other than upgrade to python3. We dropped python2 already, so this issue is most likely resolved by that.
