### ISSUE TITLE
Add support for Application Keys

### ISSUE THREAD

**Issue by bwbeach** [Backblaze/B2_Command_Line_Tool#443]
Backblaze will be adding support for multiple application keys per account, and for application keys with restricted access.

This command-line tool will need commands to create, list, and delete keys.

It will also need changes to let it authorize with restricted keys.

**Comment by bwbeach** [comment]
With application keys restricted to a single bucket, you are not allowed to call `b2_list_buckets` without specifying the name or ID of the one bucket the key is allowed to use.

When you call `b2_authorize_account`, it returns a new field called `allowed`, with the list of things the key is allowed to do, and the ID if the bucket it's restricted to (if there is a restriction).  When there is a bucket restriction, I'm thinking it would be a good idea to go ahead and get the details of that bucket and store them with the account info.  Then, when a command needs a bucket, it can check whether it's the bucket that is allowed, and print a helpful error message if not.  (For security reasons, the service just returns "not_authorized" if you try to access the wrong bucket.)

**Comment by ppolewicz** [comment]
I would leave that logic up to the server. If one day B2 server allows to modify the application keys so that they can mutate their bucket permissions or allow to authorize for many buckets, then old versions of the CLI should not return false information.

We should instead change the error messages so that they say something like "the provided application key is not allowed to access this bucket or this bucket does not exist".

I would also add a print for CLI and a return value for API to `b2_authorize_account` in the next major version, to display the contents of the `allowed` field.

**Comment by bwbeach** [comment]
@apexo - Backblaze updated the B2 service yesterday with some changes that should fix this problem.  Let me know if it keeps happening.

**Comment by eviljim** [comment]
@bwbeach this is still happening for me. I can re-authorize with the same key and b2 command line will work for an additional 24 hours, but the auth still expires and forces me to log back in again.

This happened after your post. Not sure on the exact timing, but I authorized probably sometime Saturday and it failed early AM US Pacific time; I just re-authorized with the same key and it is working again (but probably temporarily).

**Comment by bwbeach** [comment]
That's a puzzle.  I'm running version 1.3.4, and was able to use the command-line-tool just now using the auth it got last week.  

Next time it happens, could you run `b2 list-buckets --debugLogs` and let us know what's in `b2_cli.log`?

**Comment by apexo** [comment]
```
2018-08-21 18:25:58,880 20282   140272242427648 b2.api  DEBUG   calling B2Api.list_buckets(self=<b2.api.B2Api object at 0x7f93a8083400>, bucket_name=None)
2018-08-21 18:25:58,880 20282   140272242427648 b2.api  DEBUG   calling B2Api.check_bucket_restrictions(self=<b2.api.B2Api object at 0x7f93a8083400>, bucket_name=None)
2018-08-21 18:25:58,880 20282   140272242427648 b2.console_tool ERROR   ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/b2/console_tool.py", line 1388, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.5/dist-packages/b2/console_tool.py", line 755, in run
    for b in self.api.list_buckets():
  File "/usr/local/lib/python3.5/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/b2/api.py", line 256, in list_buckets
    self.check_bucket_restrictions(bucket_name)
  File "/usr/local/lib/python3.5/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/b2/api.py", line 368, in check_bucket_restrictions
    raise RestrictedBucket(allowed_bucket_name)
b2.exception.RestrictedBucket: Application key is restricted to bucket: mybucketname
```

**Comment by apexo** [comment]
Maybe just for application keys that are restricted to buckets? It in the first 24h hours after auth'ing, so the message seems to be a bit misleading, or the server is still doing weird things.

**Comment by bwbeach** [comment]
You are not allowed to use `list-buckets` with an application key restricted to a bucket.  The key lets you see just one bucket, so you can't list all the buckets.

The `get-bucket` command should work on that one bucket, though.

**Comment by apexo** [comment]
Yeah, sorry, here:

```
2018-08-21 18:36:46,971	20371	140018877400832	b2.console_tool	INFO	// ========================================  1.3.4   ======================================== \\
2018-08-21 18:36:46,972	20371	140018877400832	b2.console_tool	DEBUG	platform is Linux-[…]
2018-08-21 18:36:46,972	20371	140018877400832	b2.console_tool	DEBUG	Python version is CPython 3.5.3 […]
2018-08-21 18:36:46,972	20371	140018877400832	b2.console_tool	DEBUG	locale is ('en_US', 'UTF-8')
2018-08-21 18:36:46,972	20371	140018877400832	b2.console_tool	DEBUG	filesystem encoding is utf-8
2018-08-21 18:36:46,972	20371	140018877400832	b2.console_tool	INFO	starting command [b2.console_tool.GetBucket] with arguments: ['/usr/local/bin/b2', 'get-bucket', '--debugLogs', 'mybucketname']
2018-08-21 18:36:46,972	20371	140018877400832	b2.api	DEBUG	calling B2Api.list_buckets(self=<b2.api.B2Api object at 0x7f58aa4cb400>, bucket_name='mybucketname')
2018-08-21 18:36:46,972	20371	140018877400832	b2.api	DEBUG	calling B2Api.check_bucket_restrictions(self=<b2.api.B2Api object at 0x7f58aa4cb400>, bucket_name='mybucketname')
2018-08-21 18:36:46,972	20371	140018877400832	b2.api	DEBUG	calling B2Api.check_bucket_restrictions(self=<b2.api.B2Api object at 0x7f58aa4cb400>, bucket_name='mybucketname')
2018-08-21 18:36:47,710	20371	140018877400832	b2.api	DEBUG	calling B2Api.authorize_automatically(self=<b2.api.B2Api object at 0x7f58aa4cb400>)
2018-08-21 18:36:47,711	20371	140018877400832	b2.api	DEBUG	calling B2Api.authorize_account(self=<b2.api.B2Api object at 0x7f58aa4cb400>, realm='production') (hidden args: account_id_or_key_id, application_key)
2018-08-21 18:36:48,502	20371	140018877400832	b2.console_tool	ERROR	ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/b2/session.py", line 39, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/b2/raw_api.py", line 302, in list_buckets
    bucketName=bucket_name,
  File "/usr/local/lib/python3.5/dist-packages/b2/raw_api.py", line 159, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 55, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
b2.exception.InvalidAuthToken: Invalid authorization token. Server said:  (expired_auth_token)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/b2/console_tool.py", line 1388, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.5/dist-packages/b2/console_tool.py", line 587, in run
    for b in self.api.list_buckets(args.bucketName):
  File "/usr/local/lib/python3.5/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/b2/api.py", line 261, in list_buckets
    response = self.session.list_buckets(account_id, bucket_name=bucket_name)
  File "/usr/local/lib/python3.5/dist-packages/b2/session.py", line 43, in wrapper
    reauthorization_success = self._api.authorize_automatically()
  File "/usr/local/lib/python3.5/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/b2/api.py", line 107, in authorize_automatically
    self.account_info.get_application_key(),
  File "/usr/local/lib/python3.5/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/b2/api.py", line 126, in authorize_account
    response = self.raw_api.authorize_account(realm_url, account_id_or_key_id, application_key)
  File "/usr/local/lib/python3.5/dist-packages/b2/raw_api.py", line 163, in authorize_account
    return self._post_json(realm_url, 'b2_authorize_account', auth)
  File "/usr/local/lib/python3.5/dist-packages/b2/raw_api.py", line 159, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python3.5/dist-packages/b2/b2http.py", line 55, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
b2.exception.Unauthorized:  (unauthorized)
2018-08-21 18:36:48,505	20371	140018877400832	b2.console_tool	INFO	\\ ========================================  exit=1  ======================================== //
```

**Comment by bwbeach** [comment]
Aha!  That explains it.  Thanks!

I'll fix that.  The service is now returning a code of `unauthorized` when you try to do something that your application key doesn't allow, and the command-line tool is not handling it right.

**Comment by bwbeach** [comment]
Nope.  Jumped to conclusions.  It handles `unauthorized`, and there's already a test for that.

**Comment by bwbeach** [comment]
Is there any chance the application key you used yesterday has expired?

**Comment by bwbeach** [comment]
Ok.  I think I found it.  When it re-authorizes, it's not correctly passing in the application key; it's using the accountId instead.

Yep.  Have a failing unit test now.  🙂

**Comment by bwbeach** [comment]
Opened a new issue for this specific problem: #498
